### ISSUE TITLE
Installation instructions in readme is invalid

### ISSUE THREAD

**Issue by samuelfekete** [yoheimuta/go-protoparser#48]
Readme says to do:
```go get github.com/yoheimuta/go-protoparser/v4```
But this returns an error:
```
package github.com/yoheimuta/go-protoparser/v4: cannot find package "github.com/yoheimuta/go-protoparser/v4" in any of...
```

**Comment by samuelfekete** [comment]
Look like for Go version 1.13 it needs to be:
```GO111MODULE=on go get github.com/yoheimuta/go-protoparser/v4```

**Comment by yoheimuta** [comment]
@samuelfekete Good catch, thanks!
The GO111MODULE still defaults to auto for version 1.13.

> The GO111MODULE environment variable continues to default to auto, but the auto setting now activates the module-aware mode of the go command whenever the current working directory contains, or is below a directory containing, a go.mod file — even if the current directory is within GOPATH/src. This change simplifies the migration of existing code within GOPATH/src and the ongoing maintenance of module-aware packages alongside non-module-aware importers.

- ref. https://golang.org/doc/go1.13

I'll fix it in a moment.

**Comment by yoheimuta** [comment]
I fixed it.

- ref. https://github.com/yoheimuta/go-protoparser/blob/master/README.md#installation

**Comment by samuelfekete** [comment]
Thanks @yoheimuta
