### ISSUE TITLE
error parsring if file ends with comment _and_ no newline

### ISSUE THREAD

**Issue by kung-foo** [yoheimuta/go-protoparser#49]
```
2019/12/11 13:34:59 Lexer encountered the error "found "\x00" but expected [
] at /go/pkg/mod/github.com/yoheimuta/go-protoparser/v4@v4.0.0/internal/lexer/scanner/comment.go:12"
```

Looks like https://github.com/yoheimuta/go-protoparser/blob/master/internal/lexer/scanner/comment.go#L9-L17 is a bit too strict

**Comment by yoheimuta** [comment]
@kung-foo Thank you for your suggestion!

I agree with you. Besides, I guess allowing the comment with no newline wouldn't bother anyone.

I fixed it.

- ref. https://github.com/yoheimuta/go-protoparser/releases/tag/v4.1.0

**Comment by kung-foo** [comment]
This only came up because I selected a large part of a proto file and commented out for testing. Not because I usually write comments at the bottom of a file :)

**Comment by yoheimuta** [comment]
@kung-foo That makes sense!  Thank you for your clear explanation.
