### ISSUE TITLE
Support `option (.foo.bar) = {...}`

### ISSUE THREAD

**Issue by NotFounds** [yoheimuta/go-protoparser#63]
Hi, thanks for providing an awesome linter and library.
I'm introducing the linter to my project. And it raises an exception that `found "." but expected [TIDENT]. Use -v for more details`.

It fails at parsing like the following statement.
```proto
option (.foo.bar) = {…}
```

It seems invalid, according to https://developers.google.com/protocol-buffers/docs/reference/proto3-spec#option, but protobuf allows this syntax to change the name resolution algorithm.
cf. https://github.com/protocolbuffers/protobuf/blob/b696347f80d324c624e65a0b7e3ea5dac7ec5a41/src/google/protobuf/compiler/parser_unittest.cc#L2126-L2141

Could you support this format?

**Comment by NotFounds** [comment]
**Example**

example1.proto
```
syntax = "proto3";
package foo.bar;

import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  string name = 50000;
}
```

example2.proto
```proto3
syntax = "proto3";
package test.foo.bar;

import "example1.proto";

message Msg {
  option (.foo.bar.name) = "name";
}
```

**linter result**
```sh
$ protolint lint .
found "." but expected [TIDENT]. Use -v for more details
```

```sh
$ protolint lint -v .
(...)
2022/01/31 22:18:48 [DEBUG] Text=[(], Token=[12], Pos=[example2.proto:8:10] called from option.go:153
2022/01/31 22:18:48 [DEBUG] Text=[.], Token=[21], Pos=[example2.proto:8:11] called from fullIdent.go:8
found "." but expected [TIDENT] at /home/runner/go/pkg/mod/github.com/yoheimuta/go-protoparser/v4@v4.4.0/internal/lexer/fullIdent.go:10
```

**Comment by yoheimuta** [comment]
@NotFounds Thank you for reaching out!
The parser should support the syntax protobuf allows as much as possible. I'm looking into it.

**Comment by yoheimuta** [comment]
@NotFounds I've cut a release here: https://github.com/yoheimuta/go-protoparser/releases/tag/v4.5.1.
Can you give it a try?

**Comment by NotFounds** [comment]
@yoheimuta 
Thank you for your fix and release!
I tried to build the linter locally to use the released one and run it in my project. It works well :)

**Comment by yoheimuta** [comment]
Good to hear that!
